<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Kebijakan Privasi — Weton Online</title>
    <meta name="description" content="Kebijakan Privasi Weton Online mengenai data perhitungan, transaksi pembayaran, dan pengiriman email.">
    <link rel="canonical" href="https://weton.online/kebijakan-privasi.php">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6150985802567042" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" href="/assets/favicon.png"><link rel="stylesheet" href="assets/css/style.css">
</head>
<body><main class="site-shell"><header class="site-header"><a class="brand" href="index.php#hitung-weton"><span class="brand-mark"><span>W</span></span><span>Weton Jawa</span></a><nav class="site-nav" aria-label="Navigasi utama"><a href="index.php#hitung-weton">Home</a><a href="tentang.php">Tentang</a><a href="kebijakan-privasi.php" aria-current="page">Privasi</a><a href="kontak.php">Kontak</a></nav></header>
<article class="static-page longform-page"><header class="page-hero"><p class="eyebrow">Privasi</p><h1>Kebijakan Privasi Weton Online</h1><p class="static-lead">Halaman ini menjelaskan data yang kami proses, alasan penggunaannya, serta pilihan yang tersedia bagi Anda saat menggunakan Weton Online.</p><p class="page-updated">Terakhir diperbarui: 17 Agustus 2026</p></header>
<div class="page-divider"></div>
<section><h2>1. Ruang lingkup</h2><p>Kebijakan ini berlaku untuk penggunaan situs Weton Online, termasuk perhitungan weton, pembelian pembacaan lengkap, serta komunikasi yang Anda lakukan melalui alamat kontak kami. Dengan menggunakan situs ini, Anda memahami bahwa layanan menggunakan data yang diperlukan untuk menyediakan fungsi tersebut.</p></section>
<section><h2>2. Data yang kami proses</h2><p>Untuk menjalankan perhitungan weton, aplikasi memproses tanggal lahir dan pilihan waktu kelahiran. Data tersebut digunakan untuk menentukan hari, pasaran, dan neptu menurut aturan perhitungan yang tersedia dalam aplikasi.</p><p>Jika Anda memilih membeli pembacaan lengkap, kami juga menyimpan alamat email, identitas order transaksi, status pembayaran, nominal transaksi, metode pembayaran yang tersedia dari penyedia pembayaran, serta status pengiriman email. Kami menyimpan data kelahiran yang diperlukan agar pembacaan yang sama dapat dibuat ulang secara konsisten.</p></section>
<section><h2>3. Cara data digunakan</h2><div class="info-grid"><article><h3>Menghitung weton</h3><p>Tanggal dan waktu kelahiran digunakan untuk menghasilkan hasil perhitungan yang Anda minta.</p></article><article><h3>Memproses pesanan</h3><p>Email dan data order digunakan untuk menghubungkan pembayaran dengan pembacaan lengkap yang harus dikirim.</p></article><article><h3>Mengirim hasil</h3><p>Alamat email digunakan semata-mata untuk mengirim pembacaan lengkap setelah pembayaran terverifikasi.</p></article></div><p>Kami tidak menjual alamat email atau data transaksi kepada pihak lain untuk kepentingan pemasaran mereka.</p></section>
<section><h2>4. Pembayaran dan layanan pihak ketiga</h2><p>Pembayaran pembacaan lengkap diproses melalui Duitku. Saat transaksi berlangsung, penyedia pembayaran dapat memproses informasi yang diperlukan untuk menyelesaikan pembayaran berdasarkan kebijakan mereka sendiri. Weton Online tidak meminta atau menyimpan detail instrumen pembayaran seperti nomor kartu atau PIN Anda.</p><p>Email dikirim melalui layanan SMTP yang dikonfigurasi untuk Weton Online. Layanan ini hanya digunakan untuk menyampaikan pembacaan dan pemberitahuan yang berkaitan dengan pesanan Anda.</p></section>
<section><h2>5. Keamanan data</h2><p>Data transaksi diakses melalui koneksi server dan query database terparameterisasi. Status pembayaran ditentukan oleh callback dan verifikasi server-side, bukan oleh informasi yang dikirim browser. Kredensial database, SMTP, dan layanan pembayaran disimpan dalam konfigurasi server dan tidak dikirimkan ke halaman website.</p><p>Meski kami berupaya menerapkan pengamanan yang wajar, tidak ada metode transmisi atau penyimpanan digital yang dapat dijamin sepenuhnya bebas risiko. Kami menyarankan Anda untuk tidak mengirim password, PIN, kode OTP, atau informasi pembayaran sensitif melalui halaman kontak maupun email.</p></section>
<section><h2>6. Penyimpanan dan penghapusan data</h2><p>Data pesanan disimpan selama diperlukan untuk mengelola transaksi, pengiriman pembacaan, penanganan pertanyaan, dan kewajiban administratif yang relevan. Anda dapat meminta informasi atau penghapusan data transaksi tertentu dengan menghubungi kami dan menyertakan alamat email yang dipakai saat pesanan serta merchant order ID bila tersedia.</p><p>Permintaan akan diproses setelah kami dapat memverifikasi bahwa permintaan tersebut berkaitan dengan data Anda. Sebagian data mungkin tetap disimpan apabila diperlukan untuk memenuhi kewajiban hukum, pencegahan penyalahgunaan, atau pencatatan transaksi yang sah.</p></section>
<section><h2>7. Cookie dan pengukuran</h2><p>Situs dan penyedia pihak ketiga dapat menggunakan cookie atau teknologi serupa untuk menjalankan layanan, menjaga keamanan, memahami penggunaan situs, atau menayangkan iklan bila layanan tersebut diaktifkan. Pengaturan cookie dapat dikelola melalui browser Anda. Menonaktifkan cookie tertentu dapat memengaruhi beberapa fungsi situs.</p></section>
<section><h2>8. Hak dan pertanyaan Anda</h2><p>Anda dapat menghubungi kami untuk menanyakan data pesanan, pembaruan alamat email pengiriman sebelum diproses, atau penghapusan data yang memenuhi syarat. Untuk keamanan, jangan sertakan kredensial atau informasi keuangan sensitif dalam pesan Anda.</p><p>Hubungi kami melalui halaman <a href="kontak.php">Kontak Weton Online</a>. Kami akan berupaya merespons pertanyaan pada hari kerja.</p></section>
<section><h2>9. Perubahan kebijakan</h2><p>Kebijakan ini dapat diperbarui dari waktu ke waktu seiring perkembangan layanan atau kewajiban yang berlaku. Tanggal pembaruan di bagian atas halaman menunjukkan versi terbaru. Kami menyarankan Anda membaca kembali halaman ini secara berkala.</p></section>
<section class="page-callout"><h2>Butuh bantuan?</h2><p>Untuk pertanyaan tentang data, email hasil, atau pesanan pembacaan lengkap, gunakan halaman kontak kami.</p><a class="text-button" href="kontak.php">Buka Halaman Kontak <span aria-hidden="true">→</span></a></section>
</article></main><footer class="site-footer"><p>© <?= date('Y') ?> Weton Online · Warisan kalender Jawa, hadir dalam bentuk digital.</p><nav><a href="index.php#hitung-weton">Hitung Weton</a><a href="tentang.php">Tentang</a><a href="kontak.php">Kontak</a></nav></footer></body></html>
