<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Kebijakan Privasi — Weton Online</title>
    <meta name="description" content="Kebijakan Privasi Weton Online mengenai data perhitungan, transaksi pembayaran, dan pengiriman email.">
    <link rel="canonical" href="https://weton.online/kebijakan-privasi.php">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6150985802567042" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" href="/assets/favicon.png"><link rel="stylesheet" href="assets/css/style.css">
</head>
<body><main class="site-shell"><header class="site-header"><a class="brand" href="index.php#hitung-weton"><span class="brand-mark"><span>W</span></span><span>Weton Jawa</span></a><nav class="site-nav" aria-label="Navigasi utama"><a href="index.php#hitung-weton">Home</a><a href="tentang.php">Tentang</a><a href="kebijakan-privasi.php" aria-current="page">Privasi</a><a href="kontak.php">Kontak</a></nav></header>
<article class="static-page longform-page editorial-page privacy-page">
    <header class="page-hero"><p class="eyebrow">Privasi</p><h1>Kebijakan Privasi Weton Online</h1><p class="static-lead">Halaman ini menjelaskan data yang kami proses, alasan penggunaannya, dan pilihan yang tersedia saat Anda menggunakan Weton Online.</p><p class="page-updated">Terakhir diperbarui: 17 Agustus 2026</p></header>
    <div class="page-divider"></div>
    <aside class="privacy-summary"><strong>Ringkasan singkat</strong><p>Kami memproses data yang diperlukan untuk menghitung weton, menangani pesanan, dan mengirim hasil ke email. Kami tidak menjual alamat email atau data transaksi untuk pemasaran pihak lain.</p></aside>
    <nav class="article-nav" aria-label="Daftar isi"><p>Ringkasan kebijakan</p><a href="#data">Data yang diproses</a><a href="#tujuan">Cara data digunakan</a><a href="#pihak-ketiga">Pembayaran &amp; pihak ketiga</a><a href="#hak">Pilihan Anda</a></nav>
    <section><h2>1. Ruang lingkup</h2><p>Kebijakan ini berlaku untuk penggunaan situs Weton Online, termasuk perhitungan weton, pembelian pembacaan lengkap, dan komunikasi melalui halaman kontak. Dengan menggunakan layanan, Anda memahami bahwa kami memproses data yang diperlukan untuk menjalankan fungsi tersebut.</p><p>Kebijakan ini tidak mencakup praktik situs atau layanan lain yang mungkin Anda buka melalui tautan eksternal. Kami menyarankan Anda membaca kebijakan privasi layanan tersebut secara terpisah.</p></section>
    <section id="data"><h2>2. Data yang kami proses</h2><div class="data-table" role="region" aria-label="Ringkasan data"><div class="data-table-row data-table-heading"><span>Jenis data</span><span>Contoh</span><span>Tujuan</span></div><div class="data-table-row"><span data-label="Jenis data">Data perhitungan</span><span data-label="Contoh">Tanggal lahir dan pilihan waktu lahir</span><span data-label="Tujuan">Menghasilkan weton, hari, pasaran, dan neptu.</span></div><div class="data-table-row"><span data-label="Jenis data">Data pesanan</span><span data-label="Contoh">Email, ID order, nominal, status transaksi</span><span data-label="Tujuan">Memproses pembelian dan mengirim hasil lengkap.</span></div><div class="data-table-row"><span data-label="Jenis data">Data teknis terbatas</span><span data-label="Contoh">Cookie atau informasi penggunaan yang disediakan browser/layanan terkait</span><span data-label="Tujuan">Menjalankan, mengamankan, dan memahami penggunaan situs.</span></div></div><p>Jika Anda membeli pembacaan lengkap, data kelahiran yang relevan dapat disimpan bersama pesanan agar hasil yang sama dapat dibuat ulang dan dikirim secara konsisten. Kami tidak meminta password, PIN, kode OTP, atau detail kartu pembayaran melalui formulir situs.</p></section>
    <section id="tujuan"><h2>3. Cara data digunakan</h2><div class="info-grid"><article><h3>Menghitung weton</h3><p>Tanggal dan waktu kelahiran digunakan untuk menghasilkan hasil perhitungan yang Anda minta.</p></article><article><h3>Memproses pesanan</h3><p>Email dan data order digunakan untuk menghubungkan pembayaran dengan pembacaan lengkap.</p></article><article><h3>Mengirim hasil</h3><p>Alamat email digunakan untuk mengirim hasil dan pemberitahuan yang berkaitan dengan pesanan.</p></article></div><p>Kami tidak menjual alamat email, data kelahiran, atau data transaksi kepada pihak lain untuk kepentingan pemasaran mereka. Kami juga tidak menggunakan data perhitungan untuk membuat keputusan otomatis yang berdampak hukum atau serupa terhadap Anda.</p></section>
    <section id="pihak-ketiga"><h2>4. Pembayaran, email, dan layanan pihak ketiga</h2><p>Pembayaran pembacaan lengkap diproses melalui DOKU Checkout. Ketika Anda melanjutkan transaksi, penyedia pembayaran dapat memproses informasi yang diperlukan untuk menyelesaikan pembayaran berdasarkan kebijakan mereka sendiri. Weton Online tidak meminta atau menyimpan nomor kartu, PIN, maupun kredensial pembayaran Anda.</p><p>Email hasil dikirim melalui layanan SMTP yang dikonfigurasi untuk Weton Online. Layanan ini digunakan untuk menyampaikan pembacaan dan pemberitahuan yang terkait dengan pesanan, bukan untuk mengirim promosi yang tidak Anda minta.</p><p>Situs dapat memuat layanan pihak ketiga seperti penyedia iklan atau analitik bila diaktifkan. Layanan tersebut dapat menggunakan cookie atau teknologi serupa sesuai kebijakan masing-masing.</p></section>
    <section><h2>5. Keamanan data</h2><p>Kami menggunakan pengamanan yang wajar untuk membatasi akses ke data pesanan. Status pembayaran ditentukan melalui callback dan verifikasi di sisi server, bukan hanya berdasarkan informasi dari browser. Kredensial database, email, dan layanan pembayaran disimpan di konfigurasi server serta tidak ditampilkan di halaman situs.</p><p>Namun, tidak ada metode transmisi atau penyimpanan digital yang sepenuhnya bebas risiko. Untuk membantu menjaga keamanan Anda, jangan kirim password, kode OTP, PIN, atau informasi pembayaran sensitif melalui halaman kontak maupun email.</p></section>
    <section><h2>6. Penyimpanan dan penghapusan data</h2><p>Data pesanan disimpan selama diperlukan untuk mengelola transaksi, mengirim pembacaan, menangani pertanyaan, mencegah penyalahgunaan, dan memenuhi kewajiban administratif atau hukum yang berlaku. Periode penyimpanan dapat berbeda sesuai jenis data dan kebutuhan tersebut.</p><p>Anda dapat meminta informasi atau penghapusan data transaksi tertentu dengan menyertakan alamat email yang digunakan saat pesanan dan merchant order ID bila tersedia. Kami akan memverifikasi permintaan secara wajar sebelum memprosesnya. Sebagian data mungkin tetap perlu disimpan apabila diwajibkan hukum atau diperlukan untuk pencatatan transaksi yang sah.</p></section>
    <section><h2>7. Cookie dan pengukuran</h2><p>Cookie adalah berkas kecil yang disimpan browser untuk membantu fungsi situs atau layanan terkait. Situs dan penyedia pihak ketiga dapat memakai cookie untuk menjaga keamanan, memahami penggunaan situs, atau menayangkan iklan bila layanan tersebut aktif.</p><p>Anda dapat mengelola atau menghapus cookie melalui pengaturan browser. Menonaktifkan cookie tertentu dapat memengaruhi kenyamanan atau fungsi layanan pihak ketiga di situs.</p></section>
    <section id="hak"><h2>8. Pilihan dan hak Anda</h2><p>Anda dapat menghubungi kami untuk menanyakan data pesanan, memperbarui alamat email pengiriman sebelum pesanan diproses, atau meminta penghapusan data yang memenuhi syarat. Untuk keamanan, jangan menyertakan informasi keuangan sensitif dalam pesan Anda.</p><p>Hubungi kami melalui halaman <a href="kontak.php">Kontak Weton Online</a>. Kami akan berupaya merespons pertanyaan pada hari kerja.</p></section>
    <section><h2>9. Perubahan kebijakan</h2><p>Kebijakan ini dapat diperbarui dari waktu ke waktu seiring perkembangan layanan, teknologi, atau kewajiban yang berlaku. Tanggal pembaruan di bagian atas halaman menunjukkan versi terbaru. Kami menyarankan Anda membaca halaman ini secara berkala.</p></section>
    <section class="page-callout"><h2>Butuh bantuan?</h2><p>Untuk pertanyaan tentang data, email hasil, atau pesanan pembacaan lengkap, gunakan halaman kontak kami.</p><a class="text-button" href="kontak.php">Buka Halaman Kontak <span aria-hidden="true">→</span></a></section>
</article></main><footer class="site-footer"><p>© <?= date('Y') ?> Weton Online · Warisan kalender Jawa, hadir dalam bentuk digital.</p><nav><a href="index.php#hitung-weton">Hitung Weton</a><a href="tentang.php">Tentang</a><a href="kontak.php">Kontak</a></nav></footer></body></html>
