<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Tentang Weton Online</title>
    <meta name="description" content="Kenali Weton Online, ruang digital untuk mempelajari weton, neptu, dan tradisi Primbon Jawa.">
    <link rel="canonical" href="https://weton.online/tentang.php">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6150985802567042" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" href="/assets/favicon.png"><link rel="stylesheet" href="assets/css/style.css">
</head>
<body><main class="site-shell"><header class="site-header"><a class="brand" href="index.php#hitung-weton"><span class="brand-mark"><span>W</span></span><span>Weton Jawa</span></a><nav class="site-nav" aria-label="Navigasi utama"><a href="index.php#hitung-weton">Home</a><a href="tentang.php" aria-current="page">Tentang</a><a href="kebijakan-privasi.php">Privasi</a><a href="kontak.php">Kontak</a></nav></header>
<article class="static-page longform-page"><header class="page-hero"><p class="eyebrow">Tentang kami</p><h1>Mendekatkan tradisi weton kepada kehidupan hari ini.</h1><p class="static-lead">Weton Online adalah ruang digital untuk mengenal perpaduan hari, pasaran, dan neptu dalam kalender Jawa—dengan bahasa yang lebih mudah dipahami dan tetap menghormati sumber tradisinya.</p></header>
<div class="page-divider"></div>
<section><h2>Apa itu weton?</h2><p>Dalam tradisi Jawa, weton merupakan pertemuan antara satu hari dalam pekan dan satu pasaran dalam siklus lima hari: Legi, Pahing, Pon, Wage, dan Kliwon. Perpaduan tersebut melahirkan nilai neptu yang kemudian digunakan dalam beragam pembacaan Primbon Jawa.</p><p>Bagi banyak orang, weton adalah cara untuk mengenang hari kelahiran sekaligus membuka percakapan dengan warisan keluarga dan budaya. Weton Online hadir untuk membuat proses mengenal tradisi itu lebih praktis, tanpa menghilangkan sikap kritis dan penuh hormat.</p></section>
<section><h2>Yang dapat Anda pelajari di sini</h2><div class="info-grid"><article><h3>Hari, pasaran &amp; neptu</h3><p>Hitung dasar weton berdasarkan tanggal dan waktu kelahiran, termasuk penyesuaian hari dalam tradisi Jawa setelah sore hari.</p></article><article><h3>Watak kelahiran</h3><p>Baca petikan dan makna tradisional dari watak hari, pasaran, kelahiran, serta watak bayi yang tersedia dalam sumber aplikasi.</p></article><article><h3>Pembacaan lanjutan</h3><p>Kenali arah kejayaan, perbintangan, Pal Srigati, serta gambaran jodoh dan pernikahan menurut data Primbon yang digunakan.</p></article></div></section>
<section><h2>Cara kerja perhitungan</h2><ol class="reading-steps"><li><strong>Masukkan tanggal dan waktu kelahiran.</strong><span>Sistem menentukan tanggal perhitungan sesuai ketentuan waktu kelahiran yang dipilih.</span></li><li><strong>Hari dan pasaran dihitung.</strong><span>Data kalender menghasilkan nama weton serta nilai neptu hari dan pasaran.</span></li><li><strong>Hasil disusun dari data Primbon.</strong><span>Setiap bagian pembacaan memakai data dan kalkulator yang sama agar hasilnya konsisten.</span></li></ol></section>
<section><h2>Komitmen kami terhadap konteks budaya</h2><p>Bahasa Primbon sering kali lahir dari zaman dan kebiasaan yang berbeda dengan kehidupan modern. Karena itu, Weton Online berupaya menyajikan petikan sumber beserta pemaknaan yang lebih mudah dibaca, tanpa menyatakannya sebagai fakta ilmiah atau kepastian hidup seseorang.</p><blockquote class="culture-quote">“Tradisi dapat menjadi ruang refleksi: untuk mengenal akar, menimbang pengalaman, dan membuka percakapan dengan lebih bijaksana.”</blockquote><p>Kami tidak menggunakan perhitungan ini untuk menilai nilai diri seseorang, menentukan kesehatan, menjamin rezeki, atau memastikan masa depan hubungan. Keputusan penting tetap sebaiknya dibuat dengan pertimbangan pribadi, informasi yang baik, dan bantuan profesional bila diperlukan.</p></section>
<section><h2>Pembacaan lengkap melalui email</h2><p>Hasil dasar weton dapat dilihat di halaman perhitungan. Untuk pembacaan lengkap, pengguna dapat memilih pembayaran satu kali dan memasukkan alamat email. Setelah pembayaran terverifikasi oleh server, sistem membuat ulang pembacaan dari data kelahiran yang tersimpan dan mengirimkannya ke email tersebut.</p><p>Proses ini dirancang agar hasil lengkap tidak tersedia hanya dengan mengubah tampilan browser. Informasi pembayaran dan pengiriman email dijelaskan lebih lanjut dalam <a href="kebijakan-privasi.php">Kebijakan Privasi</a>.</p></section>
<section class="page-callout"><h2>Mulai dari wetonmu</h2><p>Gunakan kalkulator untuk mengetahui perpaduan hari dan pasaran kelahiranmu.</p><a class="text-button" href="index.php#hitung-weton">Hitung Weton Sekarang <span aria-hidden="true">→</span></a></section>
</article></main><footer class="site-footer"><p>© <?= date('Y') ?> Weton Online · Warisan kalender Jawa, hadir dalam bentuk digital.</p><nav><a href="index.php#hitung-weton">Hitung Weton</a><a href="kebijakan-privasi.php">Kebijakan Privasi</a><a href="kontak.php">Kontak</a></nav></footer></body></html>
