<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Tentang Weton Online</title>
    <meta name="description" content="Kenali Weton Online, ruang digital untuk mempelajari weton, neptu, dan tradisi Primbon Jawa.">
    <link rel="canonical" href="https://weton.online/tentang.php">
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6150985802567042" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" href="/assets/favicon.png"><link rel="stylesheet" href="assets/css/style.css">
</head>
<body><main class="site-shell"><header class="site-header"><a class="brand" href="index.php#hitung-weton"><span class="brand-mark"><span>W</span></span><span>Weton Jawa</span></a><nav class="site-nav" aria-label="Navigasi utama"><a href="index.php#hitung-weton">Home</a><a href="tentang.php" aria-current="page">Tentang</a><a href="kebijakan-privasi.php">Privasi</a><a href="kontak.php">Kontak</a></nav></header>
<article class="static-page longform-page editorial-page about-page">
    <header class="page-hero"><p class="eyebrow">Tentang kami</p><h1>Mendekatkan tradisi weton kepada kehidupan hari ini.</h1><p class="static-lead">Weton Online adalah ruang digital untuk mengenal perpaduan hari, pasaran, dan neptu dalam kalender Jawa—dengan bahasa yang mudah dipahami dan tetap menghormati sumber tradisinya.</p></header>
    <div class="page-divider"></div>
    <nav class="article-nav" aria-label="Daftar isi"><p>Di halaman ini</p><a href="#weton">Mengenal weton</a><a href="#cara-kerja">Cara kerja</a><a href="#prinsip">Prinsip kami</a><a href="#hasil-lengkap">Hasil lengkap</a></nav>
    <section id="weton"><h2>Mengenal weton</h2><p>Dalam tradisi Jawa, weton adalah pertemuan antara satu hari dalam pekan dan satu pasaran dalam siklus lima hari: Legi, Pahing, Pon, Wage, dan Kliwon. Setiap hari dan pasaran memiliki nilai neptu. Saat digabungkan, keduanya membentuk dasar berbagai pembacaan yang dikenal dalam Primbon Jawa.</p><p>Bagi sebagian keluarga, weton dipakai untuk mengingat hari kelahiran, menentukan momen adat, atau menjadi bahan percakapan antargenerasi. Bagi yang baru mengenalnya, weton dapat menjadi pintu masuk untuk memahami cara masyarakat Jawa membaca waktu, hubungan, dan pengalaman hidup.</p><aside class="article-note"><strong>Catatan penting</strong><p>Weton adalah bagian dari tradisi budaya dan ruang refleksi, bukan alat untuk memastikan masa depan atau menggantikan pertimbangan pribadi, ilmiah, maupun profesional.</p></aside></section>
    <section><h2>Yang dapat Anda pelajari di sini</h2><div class="info-grid"><article><h3>Hari, pasaran &amp; neptu</h3><p>Hitung weton dari tanggal dan waktu kelahiran, termasuk penyesuaian pergantian hari dalam tradisi Jawa.</p></article><article><h3>Watak kelahiran</h3><p>Kenali pembacaan tradisional mengenai hari, pasaran, watak kelahiran, dan watak bayi yang tersedia di aplikasi.</p></article><article><h3>Pembacaan lanjutan</h3><p>Jelajahi arah kejayaan, perbintangan, Pal Srigati, serta gambaran jodoh menurut data Primbon yang digunakan.</p></article></div></section>
    <section id="cara-kerja"><h2>Cara kerja perhitungan</h2><p>Kami merancang alur perhitungan sesederhana mungkin supaya Anda dapat fokus membaca hasilnya. Berikut proses yang berlangsung saat formulir dikirim.</p><ol class="reading-steps"><li><strong>Masukkan tanggal dan waktu kelahiran.</strong><span>Isi tanggal lahir serta pilih kelahiran siang atau malam. Informasi ini digunakan hanya untuk menjalankan perhitungan yang Anda minta.</span></li><li><strong>Tentukan tanggal perhitungan.</strong><span>Untuk pilihan malam, sistem menerapkan penyesuaian hari sesuai aturan yang digunakan dalam kalkulator ini.</span></li><li><strong>Hitung hari, pasaran, dan neptu.</strong><span>Kalender menghasilkan nama hari dan pasaran, lalu nilai neptu keduanya dijumlahkan.</span></li><li><strong>Susun pembacaan secara konsisten.</strong><span>Bagian watak dan pembacaan lanjutan memakai data yang terhubung dengan hasil neptu tersebut.</span></li></ol></section>
    <section id="prinsip"><h2>Prinsip kami dalam menyajikan tradisi</h2><p>Bahasa Primbon lahir dari konteks sejarah dan kebiasaan yang berbeda dengan kehidupan modern. Karena itu, kami berusaha menyajikannya sebagai pengetahuan budaya: dapat dibaca, direnungkan, dan dibicarakan dengan terbuka tanpa harus dianggap sebagai kepastian mutlak.</p><blockquote class="culture-quote">“Tradisi dapat menjadi ruang refleksi: untuk mengenal akar, menimbang pengalaman, dan membuka percakapan dengan lebih bijaksana.”</blockquote><div class="principle-list"><div><strong>Jelas konteksnya</strong><span>Hasil dijelaskan sebagai pembacaan tradisional, bukan klaim ilmiah.</span></div><div><strong>Mudah diakses</strong><span>Istilah dan alur dibuat lebih ringkas agar nyaman dibaca di perangkat apa pun.</span></div><div><strong>Dipakai dengan bijak</strong><span>Keputusan penting tentang kesehatan, keuangan, atau hubungan tetap perlu pertimbangan yang matang.</span></div></div></section>
    <section><h2>Untuk siapa Weton Online?</h2><p>Situs ini dibuat untuk siapa saja yang ingin mengenal weton: Anda yang sedang mencari hari pasaran kelahiran, ingin berbincang dengan keluarga mengenai tradisi Jawa, atau sekadar penasaran tentang makna sebuah kombinasi weton. Tidak diperlukan pengetahuan awal untuk memulai.</p><p>Kami juga memahami bahwa setiap keluarga dapat memiliki cara pemaknaan yang berbeda. Hasil di situs ini dapat menjadi referensi awal, bukan pengganti cerita, pengetahuan, atau tradisi yang hidup di keluarga Anda sendiri.</p></section>
    <section id="hasil-lengkap"><h2>Pembacaan lengkap melalui email</h2><p>Hasil dasar weton dapat dilihat langsung di halaman perhitungan. Untuk pembacaan lengkap, pengguna dapat memilih pembayaran satu kali dan memasukkan alamat email. Setelah pembayaran terverifikasi oleh server, sistem membuat ulang pembacaan dari data kelahiran yang tersimpan lalu mengirimkannya ke email tersebut.</p><p>Kami menggunakan proses verifikasi server agar pesanan dan pengiriman hasil tercatat dengan rapi. Cara kami menangani data pesanan, pembayaran, dan email dijelaskan lebih lanjut dalam <a href="kebijakan-privasi.php">Kebijakan Privasi</a>.</p></section>
    <section class="page-callout"><h2>Mulai dari wetonmu</h2><p>Gunakan kalkulator untuk mengetahui perpaduan hari dan pasaran kelahiranmu.</p><a class="text-button" href="index.php#hitung-weton">Hitung Weton Sekarang <span aria-hidden="true">→</span></a></section>
</article></main><footer class="site-footer"><p>© <?= date('Y') ?> Weton Online · Warisan kalender Jawa, hadir dalam bentuk digital.</p><nav><a href="index.php#hitung-weton">Hitung Weton</a><a href="kebijakan-privasi.php">Kebijakan Privasi</a><a href="kontak.php">Kontak</a></nav></footer></body></html>
