CREATE TABLE payments (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reference VARCHAR(100) NULL,
  merchant_order_id VARCHAR(80) NOT NULL,
  email VARCHAR(254) NOT NULL,
  birth_date DATE NOT NULL,
  birth_time ENUM('siang','malam') NOT NULL,
  weton VARCHAR(80) NOT NULL,
  neptu_hari TINYINT UNSIGNED NOT NULL,
  neptu_pasaran TINYINT UNSIGNED NOT NULL,
  total_neptu TINYINT UNSIGNED NOT NULL,
  amount INT UNSIGNED NOT NULL,
  status ENUM('PENDING','PAID','FAILED','EXPIRED') NOT NULL DEFAULT 'PENDING',
  doku_transaction_id VARCHAR(100) NULL,
  payment_method VARCHAR(80) NULL,
  payment_message VARCHAR(255) NULL,
  paid_at DATETIME NULL,
  email_sent_at DATETIME NULL,
  email_sending_at DATETIME NULL,
  email_error TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_payments_reference (reference),
  UNIQUE KEY uq_payments_merchant_order_id (merchant_order_id),
  KEY idx_payments_email (email),
  KEY idx_payments_status (status),
  KEY idx_payments_doku_transaction_id (doku_transaction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
