<?php

/** Source of truth Perbintangan menurut Primbon Jawa No. 117. */
final class PerbintanganData
{
    public const PERBINTANGAN = [
        7 => ["bintang" => "Mijan", "balaBantuan" => "Kuda", "musuh" => "Jun", "sumber" => "Banyak untung dan banyak godaan. Kesaktiannya angin, berbicara atas dasar kenyataan.", "kesaktian" => "Angin", "syarat" => "Memakai cincin bermata hijau.", "kejayaan" => "Hari Sabtu — bulan Besar.", "kemalangan" => "Hari Jumat — bulan Rejeb.", "penyakit" => "Tidak disebutkan dalam data sumber.", "makna" => "Menurut Primbon Jawa, Bintang Mijan digambarkan membawa jalan hidup yang kerap mempertemukan keuntungan dengan berbagai godaan. Sifat berbicara berdasarkan kenyataan dapat menjadi kekuatan untuk menjalani keadaan dengan jernih. Dalam tradisi ini, keseimbangan antara keteguhan dan kewaspadaan menjadi pesan yang menyertai bintang ini."],
        8 => ["bintang" => "Arab", "balaBantuan" => "Sur", "musuh" => "Kuda", "sumber" => "Memiliki sifat kedermawanan, dicintai orang, cocok mengabdi pada orang besar, dan banyak untung karena persaudaraan. Godaannya berupa harta benda.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata hitam.", "syarat" => "Memakai cincin bermata hitam.", "kejayaan" => "Hari Rabu — bulan Ruwah.", "kemalangan" => "Hari Selasa — bulan Mulud.", "penyakit" => "Tidak disebutkan dalam data sumber.", "makna" => "Menurut Primbon Jawa, Bintang Arab digambarkan memiliki ruang yang hangat dalam hubungan dengan orang lain, terutama melalui kemurahan hati dan ikatan persaudaraan. Keberuntungan dalam keterangan ini kerap datang melalui perjumpaan dan dukungan sekitar. Di sisi lain, godaan harta menjadi pengingat untuk tetap menjaga arah batin ketika pencapaian mulai bertambah."],
        9 => ["bintang" => "Kukus", "balaBantuan" => "Jun", "musuh" => "Surtan", "sumber" => "Dicintai orang besar, tinggi budinya, baik hati, dan memiliki rasa kasih sayang. Dihormati tetapi mudah bermusuhan.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata putih.", "syarat" => "Memakai cincin bermata putih.", "kejayaan" => "Hari Kamis — bulan Puasa.", "kemalangan" => "Hari Rabu — bulan Syawal.", "penyakit" => "Tidak disebutkan dalam data sumber.", "makna" => "Menurut Primbon Jawa, Bintang Kukus menggambarkan pribadi yang menyimpan kelembutan hati serta kemampuan untuk memperoleh penghormatan. Namun, cara bicara yang tegas atau hangatnya perasaan juga dapat menimbulkan gesekan dalam hubungan tertentu. Tradisi ini mengajak pemilik bintang Kukus untuk menjaga kasih sayang sebagai penyeimbang ketika menghadapi perbedaan."],
        10 => ["bintang" => "Jadi", "balaBantuan" => "Surtan", "musuh" => "Sada", "sumber" => "Banyak untung, tetapi memiliki halangan yang digambarkan melalui kuda, banteng, rusa, kijang, kambing, dan harimau. Keras hati.", "kesaktian" => "Gunungan kecil di atas bumi.", "syarat" => "Memakai cincin bermata hitam.", "kejayaan" => "Hari Rabu — bulan Rabiulawal.", "kemalangan" => "Hari Sabtu — bulan Syawal.", "penyakit" => "Tidak disebutkan dalam data sumber.", "makna" => "Menurut Primbon Jawa, Bintang Jadi digambarkan membawa daya juang yang kuat dan peluang baik dalam perjalanan hidup. Keteguhan hati dapat menjadi tenaga untuk melewati rintangan, meski dalam keadaan tertentu juga perlu dilunakkan agar tidak berubah menjadi penolakan terhadap nasihat. Pesan tradisinya terletak pada kemampuan membaca hambatan tanpa kehilangan arah."],
        11 => ["bintang" => "Dalu", "balaBantuan" => "Sada", "musuh" => "Mijan", "sumber" => "Sopan santun, enak bicaranya, dan mendapat warisan tetapi tidak menjadikan kemuliaan.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata merah.", "syarat" => "Memakai cincin bermata merah.", "kejayaan" => "Hari Jumat — bulan Dulkodah.", "kemalangan" => "Hari Selasa — bulan Jumadilakhir.", "penyakit" => "Tidak disebutkan dalam data sumber.", "makna" => "Menurut Primbon Jawa, Bintang Dalu menggambarkan pembawaan yang santun dan kemampuan berbicara yang dapat membuat orang lain merasa nyaman. Keterangan mengenai warisan yang tidak otomatis membawa kemuliaan menjadi pengingat bahwa nilai diri tumbuh dari cara seseorang menjalani apa yang dimilikinya. Dalam tradisi ini, kesederhanaan dan tata krama menjadi bagian penting dari kekuatannya."],
        12 => ["bintang" => "Kuda", "balaBantuan" => "Sumbul", "musuh" => "Sada", "sumber" => "Suka memukul, pemarah, pencemburu, keras hati, tetapi juga disebut memiliki banyak rezeki.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata merah.", "syarat" => "Memakai cincin bermata merah.", "kejayaan" => "Hari Kamis — bulan Besar.", "kemalangan" => "Hari Selasa — bulan Rejeb.", "penyakit" => "Tidak disebutkan dalam data sumber.", "makna" => "Menurut Primbon Jawa, Bintang Kuda menggambarkan tenaga dan perasaan yang bergerak kuat, sehingga kadang dapat tampak keras dalam menghadapi keadaan. Di baliknya, sumber juga menyebut adanya kelapangan rezeki dan daya untuk mengupayakan kehidupan. Keterangan ini dapat dimaknai sebagai ajakan untuk mengolah kemarahan dan kecemburuan menjadi keberanian yang lebih terarah."],
        13 => ["bintang" => "Asma", "balaBantuan" => "Mijan", "musuh" => "Arab", "sumber" => "Jangan pergi merantau, pekerja keras, musuhnya air, dan dilarang berpakaian warna kuning atau agak kuning. Disenangi sesamanya, pemalu, dihormati, dan musuhnya tidak berani.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata putih.", "syarat" => "Memakai cincin bermata putih.", "kejayaan" => "Hari Ahad — bulan Syawal.", "kemalangan" => "Hari Sabtu — bulan Ruwah.", "penyakit" => "Perut, panas, sakit kepala; dalam sumber disebut dapat sakit pada usia 20 atau 30 tahun.", "makna" => "Menurut keterangan Primbon Jawa, Bintang Asma menggambarkan pribadi yang memiliki dorongan kuat untuk bekerja dan menghadapi kehidupan dengan tenaga yang besar, tetapi juga memiliki sejumlah pantangan yang perlu diperhatikan. Sosok ini digambarkan memiliki karakter yang cukup kuat, dihormati oleh orang di sekitarnya, dan tidak mudah ditakuti oleh lawan. Dalam perjalanan hidupnya terdapat pesan untuk berhati-hati dalam memilih tempat, perjalanan, dan hal-hal yang menjadi pantangan, karena keberhasilan dalam tradisi ini juga dikaitkan dengan kemampuan menjaga keseimbangan antara kekuatan diri dan hal-hal yang harus dihindari."],
        14 => ["bintang" => "Sur", "balaBantuan" => "Arab", "musuh" => "Dalu", "sumber" => "Dihormati, bicaranya dapat dipercaya, hasil kerjanya sangat baik, senang pada permainan, dan tidak suka bekerja pada orang lain.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin berwarna putih.", "syarat" => "Memakai cincin berwarna putih.", "kejayaan" => "Hari Rabu — bulan Sapar.", "kemalangan" => "Hari Sabtu — bulan Ruwah.", "penyakit" => "Perut; dalam sumber disebut dapat sakit pada usia 12 atau 18 tahun.", "makna" => "Menurut Primbon Jawa, Bintang Sur digambarkan memiliki bobot kepercayaan dalam ucapan dan kesungguhan dalam hasil kerja. Keinginan untuk berjalan dengan cara sendiri dapat menjadi sumber kemandirian, sekaligus perlu diimbangi dengan kemampuan bekerja bersama. Dalam tradisi ini, kualitas karya dan keteguhan menjaga kepercayaan menjadi jalan yang paling menonjol."],
        15 => ["bintang" => "Jun", "balaBantuan" => "Kukus", "musuh" => "Sada", "sumber" => "Tangkas, rajin bekerja, senang berbuat baik, tetapi hatinya tidak tenang dan kurang cocok jual beli menurut sumber.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata hitam.", "syarat" => "Memakai cincin bermata hitam.", "kejayaan" => "Hari Ahad — bulan Rabiulawal.", "kemalangan" => "Hari Rabu — bulan Puasa.", "penyakit" => "Batuk darah, panas, pening.", "makna" => "Menurut Primbon Jawa, Bintang Jun menggambarkan gerak yang tangkas dan kesediaan untuk bekerja keras serta berbuat baik. Ada pula gambaran hati yang mudah gelisah, sehingga ketenangan batin menjadi hal yang layak dirawat di sela kesibukan. Pesan tradisinya bukan untuk membatasi langkah, melainkan mengajak seseorang memilih jalan yang selaras dengan watak dan pertimbangannya."],
        16 => ["bintang" => "Surtan", "balaBantuan" => "Arab", "musuh" => "Dalu", "sumber" => "Pemarah, cemburuan, keras bicaranya, dengan bentuk badan sedang dan warna kulit kuning agak kehijauan.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata hijau.", "syarat" => "Memakai cincin bermata hijau.", "kejayaan" => "Hari Rabu — bulan Syawal.", "kemalangan" => "Hari Ahad — bulan Jumadilawal.", "penyakit" => "Dalam sumber disebut pernah jatuh sakit pada usia tujuh bulan.", "makna" => "Menurut Primbon Jawa, Bintang Surtan digambarkan membawa perasaan yang kuat dan cara bicara yang tegas. Tenaga seperti ini dapat membantu seseorang bersikap jujur terhadap keadaan, meski perlu disertai ruang untuk mendengar dan menenangkan diri. Dalam tradisi ini, kelembutan bukan lawan dari ketegasan, melainkan penyeimbang yang membuat kekuatan lebih bermanfaat."],
        17 => ["bintang" => "Sada", "balaBantuan" => "Arab", "musuh" => "Mijan", "sumber" => "Sopan santun, sabar, ikhlas hatinya, manis tutur katanya, dan giat bekerja. Akan mendapatkan pertolongan pada hari yang akan datang.", "kesaktian" => "Api di dekat musuh; dalam sumber juga disebut uap beracun dan pertolongan dari wanita yang memberi makan.", "syarat" => "Memakai cincin bermata merah.", "kejayaan" => "Hari Ahad — bulan Jumadilawal.", "kemalangan" => "Hari Sabtu — bulan Besar.", "penyakit" => "Perut.", "makna" => "Menurut Primbon Jawa, Bintang Sada menggambarkan pribadi yang mengutamakan kesabaran, ketulusan, dan tutur kata yang manis. Kegigihan dalam bekerja disebut sebagai bagian penting dari perjalanannya, bersama keyakinan bahwa pertolongan dapat datang pada waktunya. Tradisi ini menempatkan ketabahan sebagai kekuatan yang tumbuh perlahan, bukan sekadar hasil yang datang seketika."],
        18 => ["bintang" => "Sumbul", "balaBantuan" => "Arab", "musuh" => "Kuda", "sumber" => "Banyak pengetahuannya, kaya, segala yang ditanam mendatangkan hasil, dan dilarang melakukan perjalanan pada malam hari karena rintangan ular.", "kesaktian" => "Dalam sumber dikaitkan dengan cincin bermata hijau.", "syarat" => "Memakai cincin bermata hijau.", "kejayaan" => "Hari Rabu — bulan Jumadilakhir.", "kemalangan" => "Hari Sabtu — bulan Dulkodah.", "penyakit" => "Tidak disebutkan dalam data sumber.", "makna" => "Menurut Primbon Jawa, Bintang Sumbul digambarkan memiliki keluasan pengetahuan dan daya untuk menumbuhkan hasil dari apa yang dikerjakan. Keterangan tentang kekayaan dan panen dalam sumber dapat dimaknai sebagai penghargaan pada ketekunan serta kemampuan merawat yang sudah dimulai. Pantangan perjalanan malam hadir sebagai bagian dari pesan kehati-hatian yang menyertai langkahnya."],
    ];

    /** @return array{bintang: string, balaBantuan: string, musuh: string, sumber: string, kesaktian: string, syarat: string, kejayaan: string, kemalangan: string, penyakit: string, makna: string} */
    public static function untukNeptu(int $totalNeptu): array
    {
        if (!array_key_exists($totalNeptu, self::PERBINTANGAN)) {
            throw new InvalidArgumentException("Data perbintangan tidak tersedia untuk total neptu tersebut.");
        }

        return self::PERBINTANGAN[$totalNeptu];
    }
}
