<?php

/** Source of truth Primbon No. 101: watak bayi menurut tanggal kelahiran. */
final class WatakBayiTanggal
{
    public const WATAK_BAYI_TANGGAL = [
        1 => ["sumber" => "angkuh, besar kemauannya tetapi jika maksudnya tidak tercapai lalu berputus asa dan tidak dapat diperbaiki oleh orang lain, menjadi urusan orang.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 1 digambarkan memiliki kemauan yang besar dan dorongan kuat untuk mencapai tujuan. Ketika harapan tidak terwujud, sumber juga mengingatkan adanya kecenderungan mudah putus asa. Dalam pemaknaan modern, keteguhan akan lebih bermanfaat bila disertai kelenturan untuk mencoba jalan lain."],
        2 => ["sumber" => "banyak anak dan sahabat tetapi tidak semuanya disayanginya, pelupa, cepat putus asa.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 2 dikaitkan dengan lingkungan pergaulan yang luas. Di balik banyaknya hubungan, sumber mengingatkan tentang sifat pelupa dan mudah menyerah. Dalam tradisi ini, menjaga perhatian pada relasi serta melatih ketekunan dapat menjadi penyeimbang yang baik."],
        3 => ["sumber" => "sederhana dan mukanya manis, hatinya keras tetapi mencintai/mudah menyayangi.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 3 digambarkan sederhana dan memiliki pembawaan yang menyenangkan. Ada keteguhan hati yang dapat tampak keras, namun juga disertai kemampuan menyayangi. Perpaduan ini dapat dimaknai sebagai kekuatan untuk menjaga kasih tanpa kehilangan prinsip."],
        4 => ["sumber" => "ingatannya kuat, pandai berbicara, banyak berfikir tentang hal yang baik.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 4 dikaitkan dengan ingatan yang kuat dan kelancaran berbicara. Sumber juga menggambarkan kecenderungan memikirkan hal-hal yang baik. Dalam kehidupan sehari-hari, kemampuan ini dapat menjadi jalan untuk menyimpan pelajaran dan membagikan gagasan yang membangun."],
        5 => ["sumber" => "pandai berbicara, suka menyakiti, pemarah tetapi suka memberi uang/makanan kepada orang, suci, tak suka boros.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 5 digambarkan pandai berbicara dan memiliki kemurahan hati. Sumber juga mencatat emosi yang kuat dan kata-kata yang kadang dapat melukai. Dalam pemaknaan modern, kepedulian yang sudah ada akan terasa lebih utuh saat disertai cara menyampaikan perasaan dengan lembut."],
        6 => ["sumber" => "bodoh, pelupa, ceroboh, malas.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 6 memuat gambaran tentang sifat pelupa, ceroboh, dan mudah menunda. Keterangan ini tidak perlu dibaca sebagai vonis, melainkan sebagai cermin tradisional tentang kebiasaan yang dapat diperbaiki. Ketelitian kecil dan rutinitas yang teratur dapat menjadi latihan yang menumbuhkan kepercayaan diri."],
        7 => ["sumber" => "pandai berbicara, suka pada wanita yang serong.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 7 dikaitkan dengan kemampuan berbicara yang menonjol. Sumber juga memuat peringatan mengenai pilihan dalam hubungan. Dalam tradisi ini, kelancaran kata akan menjadi kekuatan saat berjalan bersama tanggung jawab dan kesetiaan."],
        8 => ["sumber" => "jalan fikirannya/buah fikirannya baik, banyak sahabat, berhati-hati/menghitung baik/buruk.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 8 digambarkan memiliki pertimbangan yang baik dan banyak sahabat. Sikap berhati-hati dalam menilai baik dan buruk dapat membantu menjaga langkah. Dalam pemaknaan modern, kecermatan ini merupakan kekuatan ketika tidak berubah menjadi kekhawatiran berlebihan."],
        9 => ["sumber" => "keras hati, pemarah tetapi cepat tenang kembali, berfikirnya sedang, ikhlas jika barangnya diminta.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 9 memuat sifat hati yang kuat dan emosi yang cepat muncul namun segera reda. Sumber juga menggambarkan keikhlasan dalam memberi. Dalam tradisi ini, kemampuan kembali tenang dapat menjadi bekal untuk mengarahkan ketegasan menjadi kemurahan hati."],
        10 => ["sumber" => "pepet sumber, pelupa tapi pandai, suka menceritakan baik/buruknya orang.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 10 digambarkan memiliki kecakapan meski kadang disertai sifat pelupa. Keterangan tentang kegemaran membicarakan orang lain menjadi pengingat untuk menjaga kata-kata. Dalam kehidupan sehari-hari, kecerdasan akan lebih bermakna ketika digunakan untuk menyebarkan hal yang bermanfaat."],
        11 => ["sumber" => "berfikirnya luas, berlagak dan mengaku pandai, tahu sopan santun.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 11 dikaitkan dengan keluasan berpikir dan pemahaman terhadap sopan santun. Sumber juga mengingatkan kecenderungan ingin terlihat pandai. Dalam pemaknaan modern, pengetahuan akan terasa lebih berwibawa ketika disertai kerendahan hati."],
        12 => ["sumber" => "jika diam kurang menyenangkan, jika berbicara tepat dan dapat menyelesaikan sesuatu, tetapi suka mempunyai niat yang tersembunyi.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 12 digambarkan memiliki kata-kata yang tepat dan kemampuan menyelesaikan urusan. Ada pula pesan tentang niat yang tidak selalu mudah dibaca. Dalam tradisi ini, keterampilan berkomunikasi akan semakin kuat bila ditemani keterbukaan dalam tujuan."],
        13 => ["sumber" => "pandai berbicara, tepat dan banyak akalnya, keras hatinya tetapi hanya sebentar dan suka marah tetapi juga cepat hilang.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 13 menggambarkan pribadi yang memiliki kemampuan berbicara dengan baik dan banyak akal dalam menghadapi berbagai keadaan. Ia juga digambarkan memiliki emosi yang cukup kuat, tetapi kemarahan tersebut tidak berlangsung lama dan dapat kembali kepada keadaan yang lebih tenang. Dalam pemaknaan modern, kemampuan berpikir cepat dan berbicara menjadi kekuatan, sementara kemampuan mengelola emosi dapat menjadi penyeimbang."],
        14 => ["sumber" => "percaya pada diri sendiri, suka bicara yang baik, tahu akan perbuatan yang suci lahir dan batin.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 14 dikaitkan dengan keyakinan diri dan kecenderungan membicarakan hal yang baik. Sumber juga menggambarkan kesadaran pada tindakan yang bersih lahir batin. Dalam kehidupan sehari-hari, kepercayaan diri akan terasa paling kuat ketika tetap terbuka pada kebaikan dan tanggung jawab."],
        15 => ["sumber" => "berfikirnya cukupan, terang, banyak bicara yang suci, jadi sastrawan.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 15 digambarkan memiliki pikiran yang cukup jernih dan kecenderungan pada kata-kata yang baik. Gambaran menjadi sastrawan dapat dibaca sebagai penghargaan pada bahasa dan gagasan. Dalam tradisi ini, kejernihan bicara menjadi ruang untuk menyalurkan pengetahuan dengan indah."],
        16 => ["sumber" => "ceroboh, malu bekerja, pelupa dan jelek.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 16 memuat gambaran tentang kecerobohan, sifat pelupa, dan keraguan dalam bekerja. Bahasa sumber yang keras perlu dibaca sebagai catatan tradisional, bukan penilaian mutlak atas nilai seseorang. Dalam pemaknaan modern, keberanian mencoba dan kebiasaan bertanggung jawab dapat menjadi jalan untuk bertumbuh."],
        17 => ["sumber" => "banyak sahabatnya yang menyetujui pendapatnya, baik dan suci, sering memperhitungkan baik/buruk.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 17 dikaitkan dengan dukungan dari sahabat dan perhatian pada pertimbangan baik buruk. Sumber menggambarkan kecenderungan untuk menjaga niat yang baik. Dalam kehidupan sehari-hari, dukungan sosial akan menjadi kekuatan ketika tetap diimbangi dengan penilaian yang jernih."],
        18 => ["sumber" => "banyak akal, pandai bicara, agak suka pada wanita yang sering berbuat serong.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 18 digambarkan cakap berbicara dan memiliki banyak akal. Sumber juga membawa peringatan mengenai pilihan dalam hubungan. Dalam tradisi ini, kecerdikan dapat menemukan bentuk yang baik ketika disertai tanggung jawab terhadap perasaan sendiri dan orang lain."],
        19 => ["sumber" => "keras hatinya, sering marah tetapi hanya sebentar, suka menyumbangkan fikiran, makan, uang kepada orang.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 19 memuat ketegasan hati dan emosi yang cepat muncul tetapi tidak lama menetap. Di saat yang sama, ada gambaran suka berbagi pikiran maupun rezeki. Dalam pemaknaan modern, kemurahan hati dapat menjadi penyeimbang yang indah bagi karakter yang kuat."],
        20 => ["sumber" => "pelupa, tak suka berfikir, senang menerima pengaduan orang tentang hal baik dan buruk.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 20 digambarkan mudah lupa dan tidak selalu gemar memikirkan hal yang rumit. Namun sumber juga mencatat kesediaan mendengarkan cerita orang lain. Dalam kehidupan sehari-hari, kemampuan menjadi pendengar dapat berkembang lebih baik ketika disertai perhatian pada batas dan ketelitian."],
        21 => ["sumber" => "luas fikirannya, suka berlagak dan mengaku pandai, sopan santun dan tahu tabiat baik/jelek.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 21 dikaitkan dengan pikiran yang luas dan pemahaman atas tata krama. Sumber mengingatkan adanya kecenderungan ingin terlihat pandai. Dalam tradisi ini, keluasan pengetahuan menjadi lebih berharga saat disampaikan dengan rendah hati."],
        22 => ["sumber" => "suka berfikir, jika pendiam baik, jika banyak bicara perkataannya banyak tepat dan pengetahuannya benar.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 22 digambarkan senang berpikir dan memiliki kata-kata yang banyak benarnya ketika berbicara. Sifat tenang maupun kemampuan berbicara sama-sama dapat menjadi kekuatan. Dalam pemaknaan modern, memilih waktu yang tepat untuk menyampaikan pengetahuan membuat manfaatnya semakin terasa."],
        23 => ["sumber" => "pandai bicara, tepat, banyak akal, pemarah tetapi hanya sebentar kembali berfikir tenang.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 23 menggambarkan pribadi yang memiliki kemampuan berbicara dengan baik dan banyak akal dalam menghadapi berbagai keadaan. Ia juga digambarkan memiliki emosi yang cukup kuat, tetapi kemarahan tersebut tidak berlangsung lama dan dapat kembali kepada keadaan yang lebih tenang. Dalam pemaknaan modern, kemampuan berpikir cepat dan berbicara menjadi kekuatan, sementara kemampuan mengelola emosi dapat menjadi penyeimbang."],
        24 => ["sumber" => "suci hati, lahir batin, bicaranya banyak yang baik, luas pengetahuannya.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 24 dikaitkan dengan hati yang baik, kata-kata yang membangun, dan pengetahuan yang luas. Sumber menempatkan kejernihan lahir batin sebagai nilai yang penting. Dalam kehidupan sehari-hari, pengetahuan terasa lebih meneduhkan ketika dibagikan dengan niat baik."],
        25 => ["sumber" => "bicaranya banyak yang suci, pengetahuannya sedang, jadi sastrawan dan segala sesuatunya terang.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 25 digambarkan memiliki kecenderungan pada kata-kata yang baik dan terang. Gambaran menjadi sastrawan mengisyaratkan ruang bagi bahasa, cerita, dan pengetahuan. Dalam tradisi ini, kejelasan dalam menyampaikan gagasan menjadi kekuatan yang patut dirawat."],
        26 => ["sumber" => "jelek, pelupa berfikirnya ceroboh, pemalas (orang yang hatinya buruk).", "makna" => "Menurut keterangan Primbon Jawa, tanggal 26 memuat penilaian yang keras tentang sifat pelupa, ceroboh, dan malas. Keterangan ini perlu dibaca sebagai bagian dari bahasa tradisional, bukan kepastian tentang seseorang. Dalam pemaknaan modern, kesadaran atas kebiasaan sehari-hari dapat menjadi awal untuk melatih ketelitian, kepedulian, dan tanggung jawab."],
        27 => ["sumber" => "banyak famili/sanak saudara, suka bersatu dalam bekerja dan selalu memperhitungkan baik/buruk.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 27 digambarkan dekat dengan keluarga dan senang bekerja dalam kebersamaan. Sumber juga mencatat kecermatan dalam menimbang baik buruk. Dalam kehidupan sehari-hari, kemampuan bekerja bersama dapat menjadi kekuatan saat disertai pertimbangan yang adil."],
        28 => ["sumber" => "perkataannya tak menyenangkan, banyak bicara, agak suka wanita yang serong.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 28 memuat gambaran tentang kata-kata yang kadang terasa kurang menyenangkan. Sumber juga membawa peringatan tentang pilihan dalam hubungan. Dalam tradisi ini, kelancaran bicara dapat menjadi lebih bermanfaat ketika disertai kepekaan dan tanggung jawab."],
        29 => ["sumber" => "keras hatinya, pemarah tetapi lekas tenang, suka memberi uang/makanan kepada orang.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 29 digambarkan berhati kuat dan mudah marah, tetapi tidak lama kemudian kembali tenang. Ada pula kecenderungan gemar memberi kepada orang lain. Dalam pemaknaan modern, kemurahan hati dan kemampuan pulih dari emosi dapat menjadi penyeimbang bagi ketegasan."],
        30 => ["sumber" => "angkuh, banyak untungnya, jika terkena rintangan besar bukan menjadi masalah baginya.", "makna" => "Menurut keterangan Primbon Jawa, tanggal 30 dikaitkan dengan keberuntungan dan daya tahan saat menghadapi rintangan besar. Kesan angkuh dalam sumber dapat menjadi pengingat untuk menjaga kerendahan hati ketika berhasil melewati kesulitan. Dalam tradisi ini, kekuatan menghadapi tantangan akan lebih utuh bila tetap disertai kebijaksanaan."],
    ];

    public static function validate(): void
    {
        $keys = array_keys(self::WATAK_BAYI_TANGGAL);
        sort($keys);
        if ($keys !== range(1, 30)) {
            throw new RuntimeException("WatakBayiTanggal: tanggal keys mismatch");
        }
        foreach (self::WATAK_BAYI_TANGGAL as $tanggal => $data) {
            if (!is_string($data["sumber"] ?? null) || trim($data["sumber"]) === "" || !is_string($data["makna"] ?? null) || trim($data["makna"]) === "") {
                throw new RuntimeException("WatakBayiTanggal: data tidak lengkap untuk tanggal " . $tanggal);
            }
        }
    }

    /** @return array{sumber: string, makna: string}|null */
    public static function get(int $tanggal): ?array
    {
        return self::WATAK_BAYI_TANGGAL[$tanggal] ?? null;
    }
}

WatakBayiTanggal::validate();
