<?php

/** Source of truth Primbon No. 100: watak bayi menurut hari dan pekan kelahiran. */
final class WatakKelahiranData
{
    public const WATAK_KELAHIRAN = [
        "Jumat Kliwon" => ["sumber" => "Jika pria tidak banyak bicara, jika wanita banyak bicara tanpa memandang pria.", "makna" => "Menurut Primbon Jawa, Jumat Kliwon digambarkan memiliki cara berkomunikasi yang berbeda-beda sesuai keterangan sumber. Pembedaan laki-laki dan perempuan tersebut merupakan sudut pandang historis dalam teks tradisional, bukan ukuran ilmiah bagi seseorang. Dalam kehidupan sehari-hari, pesannya dapat dibaca sebagai ajakan untuk menemukan cara bicara yang bijak dan saling menghargai."],
        "Sabtu Legi" => ["sumber" => "Kokoh pendapatnya, pandai mencari harta serta kaya, dermawan, sebaiknya memelihara kuda.", "makna" => "Menurut Primbon Jawa, Sabtu Legi digambarkan memiliki pendirian yang kuat dan kecakapan melihat peluang. Kekuatan ini dapat memberi arah dalam usaha, terlebih ketika disertai sikap dermawan kepada sekitar. Keteguhan akan terasa lebih hangat ketika berjalan bersama kelapangan hati."],
        "Ahad Pahing" => ["sumber" => "Nampaknya angkuh, pandai, banyak akalnya, berhati-hati, perasaannya halus (pandai memutar dunia).", "makna" => "Menurut Primbon Jawa, Ahad Pahing digambarkan tajam dalam membaca keadaan dan berhati-hati saat melangkah. Kesan tegas yang muncul dari luar dapat menutupi perasaan yang sebenarnya halus. Dalam tradisi ini, kecerdikan menjadi kekuatan ketika dipakai dengan kejujuran dan kepekaan terhadap orang lain."],
        "Senin Pon" => ["sumber" => "Manis pembicaraannya, pandai mengambil hati orang lain dan dapat mencari rejeki.", "makna" => "Menurut Primbon Jawa, Senin Pon digambarkan memiliki tutur yang menyenangkan dan mudah membangun kedekatan. Kemampuan mengambil hati orang lain dapat membuka jalan dalam pergaulan maupun usaha. Kekuatan tersebut akan semakin berarti ketika dipakai dengan ketulusan, bukan sekadar untuk memperoleh hasil."],
        "Selasa Wage" => ["sumber" => "Tidak suka mengindahkan nasehat, pembicaraannya sulit diatur, tetapi jika wanita baik, dapat menyimpan uang.", "makna" => "Menurut Primbon Jawa, Selasa Wage digambarkan memiliki dorongan kuat untuk memegang cara pandangnya sendiri. Sifat ini dapat membuatnya teguh, namun juga mengingatkan pentingnya memberi ruang pada nasihat yang baik. Pembedaan gender dalam sumber adalah konteks budaya lama, sementara pesan praktisnya dapat dibaca sebagai ajakan untuk bijak mengelola suara diri dan sumber daya."],
        "Rabu Kliwon" => ["sumber" => "Pandai berbicara, fikirannya selalu tertuju pada wanita, sulit bersikap seperti pendeta (rusuh).", "makna" => "Menurut Primbon Jawa, Rabu Kliwon digambarkan memiliki kelancaran dalam berbicara dan perasaan yang mudah bergerak. Ada gambaran batin yang tidak selalu tenang, sehingga keteduhan perlu dicari dengan kesadaran diri. Dalam kehidupan sehari-hari, kemampuan berbicara akan menjadi kekuatan saat disertai tanggung jawab pada sikap dan relasi."],
        "Kamis Legi" => ["sumber" => "Luas pandangan/fikirannya, tidak suka diatasi. Jika wanita: jelek, sering bertengkar, tidak menghormati pria.", "makna" => "Menurut Primbon Jawa, Kamis Legi digambarkan memiliki pandangan yang luas dan keinginan kuat untuk berdiri dengan kemampuannya sendiri. Keinginan untuk tidak mudah diatasi dapat menjadi tenaga untuk mandiri, tetapi perlu diseimbangkan dengan kesediaan bekerja sama. Keterangan gender dalam sumber merupakan bagian dari cara pandang historisnya dan tidak patut dibaca sebagai penilaian mutlak."],
        "Jumat Pahing" => ["sumber" => "Pendiam, jika bodoh terlampau sekali tetapi jika pandai, pandai sekali. Menjadi teladan banyak orang dan banyak memiliki pengetahuan.", "makna" => "Menurut Primbon Jawa, Jumat Pahing digambarkan sebagai pribadi yang tenang dan memiliki potensi pengetahuan yang besar. Keterangan sumber menampilkan kecenderungan yang kuat pada dua sisi, sehingga proses belajar dan pengembangan diri menjadi penting. Saat potensi itu dirawat, keteladanan dapat tumbuh dengan alami melalui tindakan sehari-hari."],
        "Sabtu Pon" => ["sumber" => "Dapat menjadi ahli teknik (jika pria), jika wanita pandai mencari uang tanpa merasa malu.", "makna" => "Menurut Primbon Jawa, Sabtu Pon dikaitkan dengan kecakapan praktis dan kemampuan mencari jalan dalam urusan penghidupan. Pembedaan laki-laki dan perempuan di dalam sumber menunjukkan konteks sosial pada masa teks itu disusun. Pesan yang dapat direnungkan hari ini adalah pentingnya keterampilan, keberanian bekerja, dan kemandirian yang dijalani secara terhormat."],
        "Ahad Wage" => ["sumber" => "Mempunyai kemauan besar, jika mempunyai niat sulit dihalangi. Jika wanita, tidak baik.", "makna" => "Menurut Primbon Jawa, Ahad Wage digambarkan memiliki kemauan yang kuat ketika sudah menetapkan niat. Daya dorong ini dapat menjadi kekuatan untuk menuntaskan tujuan, selama tetap terbuka pada pertimbangan yang baik. Penilaian gender dalam sumber merupakan konteks tradisional dan tidak dapat dijadikan ukuran nilai seseorang pada masa kini."],
        "Senin Kliwon" => ["sumber" => "Berfikirnya tenang, jika masih usia muda nakal tetapi setelah usia menua berfikirnya halus.", "makna" => "Menurut Primbon Jawa, Senin Kliwon digambarkan memiliki pemikiran yang tenang dengan proses pendewasaan yang bertahap. Sisi yang lebih bebas di masa muda dapat berubah menjadi kehalusan pertimbangan seiring pengalaman. Dalam tradisi ini, perjalanan waktu dipandang sebagai ruang untuk belajar dan menata diri."],
        "Selasa Legi" => ["sumber" => "Pendiam, banyak akal, buah fikirnya baik, kurang menghargai dirinya tetapi selamat.", "makna" => "Menurut Primbon Jawa, Selasa Legi digambarkan tidak banyak bicara tetapi kaya pertimbangan dan akal. Ada pengingat agar kecakapan berpikir tidak membuat seseorang mengabaikan penghargaan terhadap dirinya sendiri. Ketika keyakinan diri tumbuh dengan wajar, buah pikiran yang baik dapat lebih mudah dibagikan."],
        "Rabu Pahing" => ["sumber" => "Sedikit angkuh, tidak senang jika ada yang mengatasi/melebihi, senang dipuji, keras pendapatnya, sebenarnya mudah untuk mendapat kecocokan.", "makna" => "Menurut Primbon Jawa, Rabu Pahing digambarkan memiliki pendirian kuat dan kebutuhan untuk dihargai. Sisi ini dapat membuatnya bersemangat mengejar kualitas, namun perlu diimbangi dengan kelapangan menerima kelebihan orang lain. Keterangan bahwa ia mudah menemukan kecocokan memberi isyarat bahwa hubungan baik tetap dapat dibangun melalui kerendahan hati."],
        "Kamis Pon" => ["sumber" => "Pesolek, angkuh, pendiam, hemat, jalan fikirannya sulit dimengerti dan tenang.", "makna" => "Menurut Primbon Jawa, Kamis Pon digambarkan tenang, hemat, dan memiliki cara berpikir yang tidak selalu mudah dibaca. Kesan menjaga diri dapat membuatnya tampak berjarak, meski di dalamnya terdapat pertimbangan yang rapi. Dalam kehidupan sehari-hari, membuka ruang komunikasi dapat membantu ketenangan itu lebih mudah dipahami orang lain."],
        "Jumat Wage" => ["sumber" => "Banyak bicara, tepat pembicaraannya, ikhlas, terang, selalu berhati-hati, tetapi sering mendapatkan rintangan.", "makna" => "Menurut Primbon Jawa, Jumat Wage digambarkan lugas dalam berbicara, tulus, dan berhati-hati dalam bertindak. Rintangan yang disebut dalam sumber dapat dibaca sebagai bagian dari perjalanan yang mengasah ketekunan. Kejernihan kata dan sikap ikhlas menjadi bekal untuk tetap berjalan ketika keadaan tidak selalu mudah."],
        "Sabtu Kliwon" => ["sumber" => "Sebenarnya bodoh tetapi berlagak pandai, malas bekerja, pelupa tetapi memiliki kesungguhan hati.", "makna" => "Menurut Primbon Jawa, Sabtu Kliwon digambarkan memiliki sisi yang mudah lupa atau belum selalu yakin pada kemampuan sendiri, tetapi menyimpan kesungguhan hati. Keterangan yang keras dalam sumber dapat dimaknai sebagai pengingat untuk bertumbuh melalui kerendahan hati dan kebiasaan yang tekun. Ketulusan dalam belajar dapat menjadi jalan untuk mengubah kelemahan menjadi daya tahan."],
        "Ahad Legi" => ["sumber" => "Pelupa, kepandaiannya kurang dipergunakan, senang pada wanita yang kurang baik/selalu serong.", "makna" => "Menurut Primbon Jawa, Ahad Legi digambarkan memiliki kemampuan yang perlu terus diasah agar tidak terlewat begitu saja. Sumber juga memuat peringatan tentang pilihan relasi, yang dapat dibaca sebagai ajakan menjaga tanggung jawab dan kejernihan hati. Dalam tradisi ini, kecakapan akan lebih bermakna bila digunakan untuk memilih langkah yang baik."],
        "Senin Pahing" => ["sumber" => "Tamak, dalam bekerja cukupan. Jika wanita, fikirannya lebih baik.", "makna" => "Menurut Primbon Jawa, Senin Pahing digambarkan memiliki keinginan yang besar, namun dalam bekerja dapat berjalan secukupnya. Keterangan ini dapat menjadi cermin untuk menyelaraskan ambisi dengan ketekunan nyata. Pembedaan gender dalam sumber adalah konteks historis, sedangkan pembelajaran yang bisa diambil ialah merawat tujuan dengan usaha yang konsisten."],
        "Selasa Pon" => ["sumber" => "Berfikirnya kurang, tidak senang membesarkan masalah. Jika wanita lebih baik, untuk isteri maupun untuk selir priayi.", "makna" => "Menurut Primbon Jawa, Selasa Pon digambarkan cenderung tidak suka memperbesar persoalan. Sikap ini dapat menumbuhkan suasana damai, asalkan tidak membuat hal penting dibiarkan tanpa penyelesaian. Pembedaan peran perempuan dalam sumber merupakan konteks masa lalu dan bukan penilaian yang berlaku sebagai kepastian."],
        "Rabu Wage" => ["sumber" => "Berfikirnya cukupan, dalam lapangan pekerjaan maju, jika wanita sering berbuat curang kepada suaminya.", "makna" => "Menurut Primbon Jawa, Rabu Wage dikaitkan dengan kemajuan dalam lapangan pekerjaan dan cara pikir yang cukup praktis. Hal ini dapat dimaknai sebagai kemampuan untuk berkembang melalui ketekunan dalam peran sehari-hari. Keterangan gender dalam sumber perlu dibaca sebagai bagian dari konteks budaya lama, bukan penilaian terhadap perempuan masa kini."],
        "Kamis Kliwon" => ["sumber" => "Berfikirnya kurang, dalam bekerja bersungguh-sungguh. Jika wanita berfikirnya cukupan.", "makna" => "Menurut Primbon Jawa, Kamis Kliwon digambarkan memiliki kesungguhan yang kuat dalam bekerja. Sekalipun sumber menilai cara pikirnya secara sederhana, ketekunan dapat menjadi dasar yang kokoh untuk terus belajar. Pembedaan gender yang muncul di dalam teks merupakan konteks historis yang perlu dibaca dengan bijak."],
        "Jumat Legi" => ["sumber" => "Pendirianya tidak tetap jika ada yang melebihi, hatinya selalu kurang senang dan merasa kecewa.", "makna" => "Menurut Primbon Jawa, Jumat Legi digambarkan mudah membandingkan diri ketika berhadapan dengan kelebihan orang lain. Perasaan kecewa dapat menjadi tanda bahwa penghargaan pada diri sendiri masih perlu dirawat. Dalam tradisi ini, keteguhan tumbuh ketika seseorang mampu melihat keberhasilan orang lain tanpa kehilangan arah hidupnya sendiri."],
        "Sabtu Pahing" => ["sumber" => "Baik pria/wanita dapat mencari keuntungan, memegang rahasia.", "makna" => "Menurut Primbon Jawa, Sabtu Pahing dikaitkan dengan kemampuan mencari keuntungan dan menjaga kepercayaan. Sifat ini dapat menjadi kekuatan dalam urusan kerja maupun pergaulan karena tidak semua hal perlu diumbar. Ketelitian dalam mengelola peluang dan rahasia menjadi pesan utama yang terasa dari keterangan tersebut."],
        "Ahad Pon" => ["sumber" => "Berfikirnya kurang, selalu percaya pada orang lain. Jika wanita, lebih baik; dapat menyimpan harta kekayaan suaminya.", "makna" => "Menurut Primbon Jawa, Ahad Pon digambarkan mudah memberi kepercayaan kepada orang lain. Keterbukaan ini dapat menghangatkan relasi, namun tetap memerlukan pertimbangan agar tidak mudah merugikan diri. Bagian yang membedakan perempuan dalam sumber merupakan konteks sosial tradisional dan tidak menjadi ukuran nilai seseorang."],
        "Senin Wage" => ["sumber" => "Berfikirnya kurang, tidak suka terhadap pendapat orang lain, berani mati dan menderita. Jika wanita, baik.", "makna" => "Menurut Primbon Jawa, Senin Wage digambarkan berani dan tahan menghadapi keadaan yang berat. Keberanian ini akan lebih berguna jika berjalan bersama kesediaan mendengar pendapat yang berbeda. Keterangan gender dalam sumber merupakan bagian dari bahasa zamannya, sedangkan ketabahan dapat direnungkan sebagai kekuatan bagi siapa pun."],
        "Selasa Kliwon" => ["sumber" => "Jika bodoh terlampau bodoh, jika pandai dapat menjadi sastrawan atau ulama.", "makna" => "Menurut Primbon Jawa, Selasa Kliwon digambarkan memiliki kemungkinan berkembang yang sangat kuat melalui pengetahuan. Sumber menampilkan dua kutub yang tajam, sehingga proses belajar dan lingkungan yang baik menjadi sangat berarti. Ketika diasah dengan tekun, bakat berbahasa atau pemikiran dapat menemukan bentuknya sendiri."],
        "Rabu Legi" => ["sumber" => "Sederhana, mau memberi/diberi. Jika wanita berfikirnya baik.", "makna" => "Menurut Primbon Jawa, Rabu Legi digambarkan sederhana dan terbuka dalam hubungan timbal balik. Kesediaan memberi maupun menerima dapat membuatnya mudah menjalin kebersamaan. Pembedaan gender dalam sumber adalah konteks tradisional, sementara nilai kesederhanaan dan kemurahan hati tetap dapat dibaca secara luas."],
        "Kamis Pahing" => ["sumber" => "Pendiam, tidak banyak berfikir, bekerja dengan bersungguh-sungguh, menjadi priayi, dicintai bangsawan, pekerjaannya cukupan.", "makna" => "Menurut Primbon Jawa, Kamis Pahing digambarkan tenang dan bersungguh-sungguh dalam bekerja. Keterangan tentang penghargaan dari lingkungan dapat dimaknai sebagai buah dari ketekunan yang dijaga tanpa banyak keributan. Dalam tradisi ini, kesederhanaan sikap tidak menutup kemungkinan seseorang memperoleh tempat yang baik."],
        "Jumat Pon" => ["sumber" => "Banyak akal fikirnya, jika tidak senang untuk selamanya tidak suka untuk bergaul kembali.", "makna" => "Menurut Primbon Jawa, Jumat Pon digambarkan kaya akal dan memiliki ingatan perasaan yang kuat. Saat terluka atau tidak nyaman, ia mungkin memilih menarik diri dalam waktu lama. Keterangan ini dapat menjadi ajakan untuk memberi ruang pada pemulihan sekaligus belajar menyampaikan batas dan kekecewaan secara sehat."],
        "Sabtu Wage" => ["sumber" => "Pelupa, kaku/keras wataknya dan kurang menyenangkan, jika tidak senang menjadi pemarah tetapi hanya sebentar.", "makna" => "Menurut Primbon Jawa, Sabtu Wage digambarkan memiliki watak yang kuat dan reaksi yang cepat ketika tidak nyaman. Kemarahan yang datang singkat dapat menjadi tanda bahwa perasaan perlu diberi ruang sebelum mengambil sikap. Dalam kehidupan sehari-hari, keluwesan dan jeda dapat membantu kekuatan karakter ini terasa lebih menenangkan."],
        "Ahad Kliwon" => ["sumber" => "Tamak, mempunyai banyak keinginan. Jika wanita: pemboros.", "makna" => "Menurut Primbon Jawa, Ahad Kliwon digambarkan memiliki banyak keinginan dan dorongan untuk memperoleh sesuatu. Energi tersebut dapat menjadi sumber semangat, asalkan diimbangi dengan kemampuan mengatur kebutuhan dan keinginan. Keterangan gender dalam sumber adalah konteks tradisional, sedangkan pelajaran tentang pengendalian diri berlaku secara lebih luas."],
        "Senin Legi" => ["sumber" => "Pendiam, tidak banyak kemauan, tenang berfikirnya. Jika wanita bekerjanya baik.", "makna" => "Menurut Primbon Jawa, Senin Legi digambarkan tenang, tidak banyak menuntut, dan cermat dalam berpikir. Kesederhanaan keinginan dapat memberi ruang untuk melihat keadaan dengan lebih jernih. Pembedaan gender dalam sumber perlu dipahami sebagai konteks masa lalu, sementara ketenangan bekerja merupakan nilai yang dapat dimiliki siapa saja."],
        "Selasa Pahing" => ["sumber" => "Pemalu, malas, kaku hatinya, rendah perbuatannya. Jika wanita, baik, berbakti pada suami.", "makna" => "Menurut Primbon Jawa, Selasa Pahing digambarkan memiliki sisi pemalu dan hati yang tidak mudah berubah. Keterangan tersebut dapat dibaca sebagai pengingat untuk membangun keberanian kecil dan keluwesan dalam menghadapi kehidupan. Bagian gender dalam sumber merupakan cara pandang historis, bukan ukuran nilai atau peran seseorang kini."],
        "Rabu Pon" => ["sumber" => "Berfikir kuat, suka bekerja, mempunyai pendirian yang tetap. Jika wanita, hemat, tetapi kaku/keras keinginannya.", "makna" => "Menurut keterangan Primbon Jawa, Rabu Pon menggambarkan pribadi yang memiliki pikiran kuat, tekun dalam bekerja, dan tidak mudah berubah dari pendiriannya. Keteguhan tersebut dapat menjadi kekuatan ketika seseorang memiliki tujuan yang jelas dan mampu mempertahankan prinsipnya. Namun, sifat yang terlalu kuat juga dapat membuat seseorang sulit menerima perubahan atau keinginan yang berbeda dari dirinya, sehingga keluwesan menjadi penyeimbang yang penting."],
        "Kamis Wage" => ["sumber" => "Bertanggung jawab, tahan menderita, keras budinya. Jika wanita, berfikirnya setengah-setengah.", "makna" => "Menurut Primbon Jawa, Kamis Wage digambarkan memiliki rasa tanggung jawab dan ketahanan saat menghadapi kesulitan. Keteguhan batin dapat menjadi kekuatan besar, meski perlu dirawat agar tidak berubah menjadi keras pada diri sendiri atau orang lain. Keterangan gender dalam sumber adalah konteks budaya lama, sedangkan pesan tentang ketabahan dapat dimaknai secara lebih luas."],
    ];

    /** @return array{sumber: string, makna: string} */
    public static function untukWeton(string $hari, string $pasaran): array
    {
        $hari = $hari === "Minggu" ? "Ahad" : $hari;
        $key = $hari . " " . $pasaran;

        if (!array_key_exists($key, self::WATAK_KELAHIRAN)) {
            throw new InvalidArgumentException("Data watak untuk weton ini belum tersedia.");
        }

        return self::WATAK_KELAHIRAN[$key];
    }
}
