<?php
/** @var array $reportForTemplate */
$r = $reportForTemplate; $n = $r['neptu'];
$e = static fn(mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$section = static function (string $title): void { echo '<h2 style="margin:28px 0 10px;padding-bottom:8px;border-bottom:1px solid #d9bd7a;color:#174033;font-family:Georgia,serif;font-size:20px">' . htmlspecialchars($title, ENT_QUOTES, 'UTF-8') . '</h2>'; };
$reading = static function (?array $item, string $source) use ($e): void { if (!$item) { echo '<p>Data tidak tersedia dalam sumber yang digunakan.</p>'; return; } echo '<p><strong>Petikan Primbon:</strong><br>' . $e($item['sumber'] ?? '-') . '</p><p><strong>Makna:</strong><br>' . $e($item['makna'] ?? '-') . '</p><p style="color:#6d6758;font-size:12px"><strong>Sumber:</strong> ' . $e($source) . '</p>'; };
?><!doctype html><html lang="id"><body style="margin:0;background:#f5efe2;color:#26372e;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:20px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fffdf8;border-radius:14px;overflow:hidden"><tr><td style="padding:30px;background:#173d31;color:#fff4dc;text-align:center"><div style="color:#f2c66d;font-family:Georgia,serif;font-size:28px;font-weight:bold">Weton Online</div><div style="margin-top:8px;font-family:Georgia,serif;font-size:18px">Pembacaan Lengkap Wetonmu</div></td></tr><tr><td style="padding:28px">
<?php $section('Data Kelahiran'); ?>
<table role="presentation" width="100%" cellpadding="6" style="border-collapse:collapse"><tr><td>Tanggal lahir</td><td><strong><?= $e($r['birthDate']) ?></strong></td></tr><tr><td>Waktu lahir</td><td><strong><?= $e($r['birthTime']) ?></strong></td></tr><tr><td>Hari</td><td><strong><?= $e($r['hari']) ?></strong></td></tr><tr><td>Pasaran</td><td><strong><?= $e($r['pasaran']) ?></strong></td></tr><tr><td>Weton</td><td><strong><?= $e($n['weton']) ?></strong></td></tr><tr><td>Neptu hari</td><td><strong><?= $e($n['neptuHari']) ?></strong></td></tr><tr><td>Neptu pasaran</td><td><strong><?= $e($n['neptuPasaran']) ?></strong></td></tr><tr><td>Total neptu</td><td><strong><?= $e($n['totalNeptu']) ?></strong></td></tr></table>
<?php $section('Watak Hari'); $reading($r['watakHari'], 'Primbon Jawa — No. 109 Watak Hari.'); ?>
<?php $section('Watak Pasaran'); $reading($r['watakPasaran'], 'Primbon Jawa — No. 110 Watak Pekan/Pasaran.'); ?>
<?php $section('Watak Kelahiran'); $reading($r['watakKelahiran'], 'Primbon Jawa — No. 100 Watak bayi menurut hari dan pekan kelahiran.'); ?>
<?php $section('Watak Bayi'); ?><h3 style="font-family:Georgia,serif;color:#8a651c">A. Menurut jumlah neptu <?= $e($n['totalNeptu']) ?></h3><?php $reading($r['watakBayi'], 'Primbon Jawa — No. 105 Watak Bayi.'); ?><h3 style="font-family:Georgia,serif;color:#8a651c">B. Menurut tanggal lahir</h3><?php $reading($r['watakBayiTanggal'], 'Primbon Jawa — No. 101 Watak bayi menurut tanggal kelahiran.'); ?>
<?php $section('Arah Kejayaan'); ?><p><strong>Total neptu:</strong> <?= $e($n['totalNeptu']) ?><br><strong>Arah kejayaan:</strong> <?= $e($r['arahKejayaan']['display']) ?></p><p style="color:#6d6758;font-size:12px">Keterangan arah berdasarkan total neptu dalam data Weton Online.</p>
<?php $section('Perbintangan'); $b = $r['perbintangan']; ?><p><strong>Nama bintang:</strong> <?= $e($b['bintang']) ?></p><p><strong>Petikan Primbon:</strong><br><?= $e($b['sumber']) ?></p><p><strong>Makna:</strong><br><?= $e($b['makna']) ?></p><table role="presentation" width="100%" cellpadding="6" style="border-collapse:collapse;background:#faf3e4"><tr><td>Bala bantuan</td><td><?= $e($b['balaBantuan']) ?></td></tr><tr><td>Musuh</td><td><?= $e($b['musuh']) ?></td></tr><tr><td>Kesaktian</td><td><?= $e($b['kesaktian']) ?></td></tr><tr><td>Syarat</td><td><?= $e($b['syarat']) ?></td></tr><tr><td>Kejayaan</td><td><?= $e($b['kejayaan']) ?></td></tr><tr><td>Kemalangan</td><td><?= $e($b['kemalangan']) ?></td></tr><tr><td>Penyakit</td><td><?= $e($b['penyakit']) ?></td></tr></table><p style="color:#6d6758;font-size:12px">Sumber: Primbon Jawa — No. 117 Perbintangan.</p>
<?php $section('Pal Srigati'); ?><p>Neptu: <strong><?= $e($n['totalNeptu']) ?></strong>. Periode aktif saat ini ditandai dengan emas.</p><table role="presentation" width="100%" cellpadding="7" style="border-collapse:collapse"><tr style="background:#173d31;color:#fff"><th align="left">Usia/periode</th><th align="left">Nilai</th></tr><?php foreach ($r['palSrigati']['timeline'] as $age => $row): $active = (int) $age === (int) $r['palSrigati']['period']; ?><tr<?= $active ? ' style="background:#f5dfaa"' : '' ?>><td><?= $e($row['label']) ?> tahun<?= $active ? ' (periode aktif)' : '' ?></td><td><strong><?= $e($row['value']) ?></strong></td></tr><?php endforeach; ?></table><p style="color:#6d6758;font-size:12px">Sumber: Primbon Jawa — No. 96 Pal Srigati.</p>
<?php $section('Jodoh & Pernikahan'); ?><p>Neptu pengguna: <strong><?= $e($n['totalNeptu']) ?></strong>. Berikut seluruh hasil dari kalkulator No. 22 dan No. 23.</p><?php foreach (['utama'=>'Rekomendasi utama','alternatif'=>'Alternatif','kurang-selaras'=>'Kurang selaras'] as $group => $label): ?><h3 style="font-family:Georgia,serif;color:#8a651c"><?= $e($label) ?></h3><?php foreach ($r['jodoh'][$group] as $match): ?><div style="margin:12px 0;padding:14px;border:1px solid #e1d4b5;border-radius:8px"><p style="margin-top:0"><strong>Neptu pasangan <?= $e($match['partnerNeptu']) ?></strong><br>Weton pasangan: <?= $e(implode(' · ', $match['wetonPasangan'])) ?><br>Total neptu pasangan: <?= $e($match['combinedNeptu']) ?></p><?php if ($match['result22']): $m22=$match['result22']; ?><p><strong>No. 22 — <?= $e($m22['nama']) ?></strong><br>Petikan/keterangan: <?= $e($m22['sumber']) ?><br>Makna: <?= $e($m22['makna']) ?></p><?php else: ?><p><strong>No. 22</strong><br>Belum tersedia untuk total ini dalam data sumber; tidak dibuatkan asumsi.</p><?php endif; $m23=$match['result23']; ?><p><strong>No. 23 — <?= $e($m23['nama']) ?></strong> (status: <?= $e($m23['status']) ?>)<br>Makna: <?= $e($m23['makna']) ?></p></div><?php endforeach; ?><?php endforeach; ?><p style="color:#6d6758;font-size:12px">Sumber: Primbon Jawa — No. 22 dan No. 23 Perhitungan untuk suami istri.</p>
<hr style="border:0;border-top:1px solid #dfd2b8"><p style="font-size:12px;color:#5d685f">Pembacaan ini merupakan bagian dari tradisi Primbon Jawa dan digunakan sebagai bahan refleksi budaya. Hasil perhitungan bukan kepastian mengenai masa depan, kecocokan, kesehatan, atau keberlangsungan sebuah hubungan.</p></td></tr></table></td></tr></table></body></html>
